### ISSUE TITLE
Create marker and interactive marker services in UWSim

### ISSUE THREAD

**Issue by marioprats** [uji-ros-pkg/underwater_simulation#1]
This would allow external nodes to dynamically create geometry in the scene through visualization_msgs/Marker and visualization_msgs/InteractiveMarker messages. Markers could be spawn upon a service call. Interactive Markers should be created by a client in UWSim, listening to a server running in a external node. See an example here: 

http://www.ros.org/wiki/osg_interactive_markers

**Comment by perezsolerj** [comment]
This is already working, issues should focus on concrete bugs / enhancements.
