### ISSUE TITLE
UWSim build error

### ISSUE THREAD

**Issue by hashmuke** [uji-ros-pkg/underwater_simulation#10]
Following the installation procedure stated in http://www.irs.uji.es/uwsim/wiki/index.php?title=Installing_UWSim the following error message apears when requested to rosmake UWSim
{-------------------------------------------------------------------------------
  [rosbuild] Building package UWSim
  [rosbuild] Including /opt/ros/fuerte/share/roscpp/rosbuild/roscpp.cmake
  [rosbuild] Including /opt/ros/fuerte/share/rospy/rosbuild/rospy.cmake
  [rosbuild] Including /opt/ros/fuerte/stacks/client_rosjava_jni/rosjava_jni/cmake/rosjava.cmake
  [rosbuild] Including /opt/ros/fuerte/share/roslisp/rosbuild/roslisp.cmake
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/hash/src/underwater_simulation/UWSim
  [  0%] Built target rospack_genmsg_libexe
  [  0%] Built target rosbuild_precompile
  Scanning dependencies of target uwsim
  [  2%] Building CXX object CMakeFiles/uwsim.dir/src/SimulatedIAUV.o
  In file included from /home/hash/src/underwater_simulation/UWSim/src/ROSInterface.h:29:0,
                   from /home/hash/src/underwater_simulation/UWSim/src/SceneBuilder.h:21,
                   from /home/hash/src/underwater_simulation/UWSim/src/SimulatedIAUV.cpp:13:
  /home/hash/src/underwater_simulation/UWSim/src/BulletPhysics.h:20:38: fatal error: osgbDynamics/MotionState.h: No such file or directory
  compilation terminated.
  make[2]: **\* [CMakeFiles/uwsim.dir/src/SimulatedIAUV.o] Error 1
  make[1]: **\* [CMakeFiles/uwsim.dir/all] Error 2
-------------------------------------------------------------------------------}

**Comment by marioprats** [comment]
Hi, thanks for the report.
Does your ROS_PACKAGE_PATH environment variable include the 'underwater_simulation' directory?

**Comment by hashmuke** [comment]
Yes, I have both the underwater_simulation and UWSim under my ROS_PACKAGE_PATH environment variable.

**Comment by marioprats** [comment]
Could you please paste the contents of your ROS_PACKAGE_PATH variable and
your underwater_simulation directory?

**Comment by hashmuke** [comment]
Here you go,
{----------
 echo $ROS_PACKAGE_PATH
/home/hash/src/:/home/hash/src/underwater_simulation/:/home/hash/fuerte_workspace/:/home/hash/fuerte_workspace/stacks:/home/hash/fuerte_workspace/turtlebot:/home/hash/fuerte_workspace/sandbox:/opt/ros/fuerte/stacks:/opt/ros/fuerte/share:/opt/ros/fuerte/share/ros:/opt/ros/fuerte/share:/opt/ros/fuerte/stacks
---------}
{--------
hash@hash:~/src/underwater_simulation$ ls
build
CMakeCache.txt
CMakeFiles
cmake_install.cmake
CMakeLists.txt
Makefile
osgBullet
osgOcean
osgWorks
rosdep.yaml
stack.xml
underwater_sensor_msgs
underwater_vehicle_dynamics
UWSim
-------}

**Comment by hashmuke** [comment]
Well it seems that I managed to solve the problem. Apparently, it turn out to be a problem with an incomplete osgBullet library. It was missing the include directory. I got a copy of the library from https://code.google.com/p/osgbullet/wiki/DownloadPage#Source and now everything is safe.
