### ISSUE TITLE
groovy-devel and hydro-devel are way behind master

### ISSUE THREAD

**Issue by tut-yury** [uji-ros-pkg/underwater_simulation#11]
Both devel branches were created in April and lack all the changes/fixes introduced later. Just started working on UWSim on hydro and ubuntu 13.04 and had to change quite a lot of configs to make it compile (UWSim still doesn't compile currently with link error).
Are there any plans on merging/rebasing groovy-devel and hydro-devel branches with master?

**Comment by tut-yury** [comment]
Solved for now by installing 12.04 and groovy.
But it would be nice really nice to stay up-to-date and use catkin and hydro...

**Comment by perezsolerj** [comment]
Hi,

We are migrating to groovy / hydro soon (a month or so), and then we will start developing new features for them leaving fuerte branch without updates. Sorry for the incovenience.

**Comment by tut-yury** [comment]
I am (and we are) looking forward to this migration :)
No problem, will be working on new features too :)

**Comment by marioprats** [comment]
Thanks for @tut-yury for bringing this up. 
@perezsolerj tell me when you are ready and I can do the rebase. There were significant changes in the directory structure for a rebase to work out of the box

**Comment by tut-yury** [comment]
Ok, now the hydro and groovy devel branches are up to date.
How do you plan to proceed further? Will you create fuerte-devel for older code and merge master into hydro/groovy-devel and continue keeping master as a branch for lastest stable code?
Or will the master be for fuerte and devel branches will be for hydro and groovy?
For me the fuerte-devel for fuerte and master for groovy/hydro development (with hydro/groovy-devel for binary ROS distribution, i.e. stable branshes) is a better way to go, but this is totally up to you guys. 
Just let me know which branch should I fork to create new pull requests :)

**Comment by marioprats** [comment]
I would suggest renaming master to fuerte-devel, therefore having three devel branches corresponding to the three supported ROS distributions. Everyone should develop in the latest devel branch (hydro-devel now). The other ones should be frozen except for (compatible) bugfixes that can be cherry-picked from the latest development branch. That was the policy followed at Willow Garage and worked well. So, you should work in hydro-devel now, and issue pull requests to that branch.
