### ISSUE TITLE
Follow a code style

### ISSUE THREAD

**Issue by marioprats** [uji-ros-pkg/underwater_simulation#19]
As UWSim grows we should start paying more attention to code style and rules. Since UWSim is strongly integrated with ROS, I suggest adopting the ROS coding style:

http://wiki.ros.org/CppStyleGuide

If you use an IDE, in the following link you can find some style templates you can use:

http://wiki.ros.org/IDEs

I'm planning to auto-format all the existing files according to the ROS style. Please tell me when you think is a good moment. Changing the style may cause a lot of problems for merges, so let's do it when you are in sync with this repository and without pending pull requests.

**Comment by tut-yury** [comment]
I couldn't agree more about styles. From my side now is a good time to reformat the code :).

**Comment by marioprats** [comment]
Merged, now let's try to keep it ;)
