### ISSUE TITLE
Changes in scenes or shaders need compilation

### ISSUE THREAD

**Issue by perezsolerj** [uji-ros-pkg/underwater_simulation#24]
As the new way to build the simulator if you change something in scenes or shaders, this won't be active unless you compile the whole package. The real files are on install/share/uwsim and if you change that ones then building overwrites them...

Is there a way to fix this?

**Comment by marioprats** [comment]
With catkin, packages are 'installed', and the installed versions are the ones that are used. Each time the package is installed, the old install is overwritten by the new one. So, if you are working on a shader or scene, you will need to call 'catkin_make install' afterwards.

**Comment by miquelmassot** [comment]
Is it possible to move shaders and scenes to '~/.uwsim' so that the 'catkin_make install' command is not needed?

**Comment by perezsolerj** [comment]
I don't think moving them is the right option as this way shaders are under version control which is desirable in my opinion.

As there seems to be no other way (and I already got used to it)  I'll close this.
