### ISSUE TITLE
Build error linking travis

### ISSUE THREAD

**Issue by perezsolerj** [uji-ros-pkg/underwater_simulation#29]
Travis build fail when linking libuwsim.so 

Linking CXX shared library /home/travis/ros/ws_uwsim/devel/lib/libuwsim.so
/usr/bin/ld: cannot find -lorocos-kdl

**Comment by tut-yury** [comment]
I also get the same error, I just updated my code...
Does the new code requires taking robot_state_publisher from source? I took it and it still teeling me that 
"ROSInterface.cpp:1030:104: error: no matching function for call to ‘robot_state_publisher::RobotStatePublisher::publishTransforms(std::mapstd::basic_string<char, double>&, ros::Time, std::string&)’"

I'm wondering why my SimulatedDevice interface wasn't used for this? With it, it is possible to make another package, which depends on both uwsim and robot_state_publisher and provides plugin for TF publishing...

Rolling back for now...

**Comment by perezsolerj** [comment]
Hi,

The error is caused by robot_state_publisher old interface. It has been changed but it's not in binary package yet, discussed on #25 . So we are using it from source by now. I will update installing wiki soon (I'm updating the whole wiki) with that issue but I hope binaries will be updated soon.

This issue is about another error, that appears to happen on travis build, working it...

About the SimulatedDevice interface maybe it's true we should use it for every interface... as soon as I update TF publisher I'll change it. 

Sorry for all the incovenience caused

**Comment by tut-yury** [comment]
NP, I also get "cannot find -lorocos-kdl" when linking my library with simulated devices.
You can solve this problem by moving TF publisher to another library by using SimulatedDevice's pluginlib technology... I guess only TF publisher uses kdl_orocos...

**Comment by perezsolerj** [comment]
Solved in 1b55a5bde348b40d8ce7dc53ba4c13d2a98de069
