### ISSUE TITLE
Path for textures

### ISSUE THREAD

**Issue by marioprats** [uji-ros-pkg/underwater_simulation#3]
When a model has a texture, it seems that the texture file has to be stored inside UWSim/data/textures for it to be loaded. This prevents users from having external folders with models and textures. 
Should check where OSG looks for textures, and add to the standard path those defined by the user with the --dataPath option

**Comment by perezsolerj** [comment]
I was trying to solve this and realized it is already working?.

I added a textured object and placed the texture in an external folder. Loading the scene without --dataPath results in non-textured object but if i add --dataPath "texturefolder" it works. Tried for vehicles and objects, both work. 

Did I miss something? or it was eventually solved but no one closed the issue?. Maybe it has something to do with osgversion or shaders... no idea :S

**Comment by marioprats** [comment]
That's great, auto-fixing github issues ;)
I guess we can close the ticket and reopen it if it doesn't work for someone
Thanks @perezsolerj
