### ISSUE TITLE
Running UWSim from a server

### ISSUE THREAD

**Issue by miquelmassot** [uji-ros-pkg/underwater_simulation#33]
As we all know, uwsim is not lightweight in terms of graphics and cpu process, so I intended to run it on a server machine instead of on my own laptop to free up cpu and graphics. 
However, when I run uwsim through ssh it's not possible, here's the output:

```
$ rosrun uwsim uwsim
Starting UWSim...
Loading SimulatedDevices plugin: 'SimDev_Echo_Factory'
  . Setting localized world: 0.00118s
Loading URDF robot... 
  · robot/GIRONA500/g500_March11.osg: 1.2619s
  · robot/ARM5E/ARM5E_part0.osg: 0.042751s
  · robot/ARM5E/ARM5E_part1.osg: 0.042831s
  · robot/ARM5E/ARM5E_part2.osg: 0.058096s
  · robot/ARM5E/ARM5E_part3.osg: 0.215907s
  · robot/ARM5E/ARM5E_part4_base.osg: 0.199131s
  · robot/ARM5E/ARM5E_part4_jaw1.osg: 0.038184s
  · robot/ARM5E/ARM5E_part4_jaw2.osg: 0.037616s
  · Linking links...Robot successfully loaded. Total time: 0.000758s
1.8975s
[ INFO] [1389865946.737459232]: Loaded tree, 7 segments, 6 joints
Xlib:  extension "NV-GLX" missing on display "localhost:10.0".
[ INFO] [1389865948.735544463]: ROSOdomToPAT subscriber on topic /dataNavigator
[ INFO] [1389865948.739279321]: ArmToROSJointState publisher on topic /uwsim/joint_state
[ INFO] [1389865948.739430484]: ROSJointStateToArm subscriber on topic /uwsim/joint_state_command
[ INFO] [1389865948.739592863]: VirtualCameraToROSImage publisher on topic /uwsim/camera1_info
[ INFO] [1389865948.764002390]: ROSTwistToPAT subscriber on topic /g500/twist
[ INFO] [1389865948.764154058]: RangeSensorToROSRange publisher on topic /uwsim/g500/range
[ INFO] [1389865948.764229583]: ROSPoseToPAT subscriber on topic /g500/pose
[ INFO] [1389865948.764365247]: GPSSensor publisher on topic g500/gps
[ INFO] [1389865948.764415839]: VirtualCameraToROSImage publisher on topic /uwsim/rangecamera_info
[ INFO] [1389865948.764517263]: DVLSensor publisher on topic g500/dvl
[ INFO] [1389865948.766239231]: Imu publisher on topic g500/imu
[ INFO] [1389865948.766329930]: PressureSensor publisher on topic g500/pressure
[ INFO] [1389865948.790178842]:  MultibeamSensorToROS publisher on topic g500/multibeam
[ INFO] [1389865948.790325608]: SimDev_Echo_ROSPublisher on topic g500/echo1
[ INFO] [1389865948.790573663]: SimDev_Echo_ROSPublisher on topic g500/echo2
[ INFO] [1389865948.883851279]: contactSensorToROS publisher on topic g500/contactSensor
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
uwsim_binary: ../../src/xcb_io.c:736: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
/home/ros/hydro/src/uib-ros/underwater_simulation/uwsim/src/uwsim: line 22:  2453 Aborted                 (core dumped) rosrun uwsim uwsim_binary --dataPath ~/.uwsim/data $@
```

is this problem related with ssh and X-forwarding or it's uwsim related? Have you tried running uwsim remotely?

**Comment by perezsolerj** [comment]
I can't help too much with it because I have never tried to run UWSim from a server. But I googled a little bit about the error and I read many issues related to GLwidgets. The only widgets we use are virtual cameras. So, maybe you can try to run a scene without any camera sensors and see what happens. Sensors that do use cameras are VirtualCameras, RangeCameras, Multibeam and StructuredLightProjector. 

You can also comment the code that creates the widgets on ViewBuilder lines 154 - 184. This should prevent widget creation.

But as I said before is just an idea googling the error....

**Comment by marioprats** [comment]
From my experience, if you want to run UWSim remotely, but see the window locally through X-forwarding, I'm not sure that's possible because it needs a lot of hardware-related stuff, and there's no direct connection between the window and the graphics hardware through ssh. However, it should be possible to start everything (including the window) remotely through ssh, and just interact locally with ROS interfaces. You won't be able to see the window though, unless you have physical access to the remote machine. I did this once with gazebo, although it needed some configuration that I cannot remember now :(

**Comment by miquelmassot** [comment]
Hi Mario, that's exactly what I want. I want to perform a bunch of
simulations and I don't really care seeing or not the simulator in real
time, but the image topics through the network. Is it maybe possible to run
UWSim without showing the window? Today I haven't had time to test what
Javier suggested, I'll try ASAP.

On 17 January 2014 17:49, marioprats notifications@github.com wrote:

> From my experience, if you want to run UWSim remotely, but see the window
> locally through X-forwarding, I'm not sure that's possible because it needs
> a lot of hardware-related stuff, and there's no direct connection between
> the window and the graphics hardware through ssh. However, it should be
> possible to start everything (including the window) remotely through ssh,
> and just interact locally with ROS interfaces. You won't be able to see the
> window though, unless you have physical access to the remote machine. I did
> this once with gazebo, although it needed some configuration that I cannot
> remember now :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uji-ros-pkg/underwater_simulation/issues/33#issuecomment-32622461
> .

## 

Miquel Massot

miquel.massot@gmail.com
http://www.facebook.com/massothttp://www.twitter.com/resisteixhttp://gplus.to/massot

**Comment by marioprats** [comment]
I don't know if it's possible to run it headless, I don't think so... but you should be able run it on a remote window. Have a look to this post about gazebo:

http://answers.gazebosim.org/question/2153/drcsim-cant-figure-out-how-to-run-gazebo-on-remote/

The trick is that you need a user logged in in the remote machine. You will need a good graphics card and its drivers installed remotely too. With that, setting the DISPLAY variable should do the job.

**Comment by tut-yury** [comment]
If I need to run uwsim remotely, I usually connect to a server (with desktop environment running) through ssh with port forwarding, i.e. "ssh -L15900:127.0.0.1:5900 user@host" and start "x11vnc", which starts a vnc server. After it tells you that it runs on port 5900, just make a connection with vnc client to localhost:15900 on the client machine...
SSH will forward your local port 15900 to server's 5900 and you will be able to do all the things you do with a desktop, including UWSim...
I personally never tried to run UWSim using ssh with X-forwarding (-X option).

**Comment by miquelmassot** [comment]
Correct @tut-yury , that's how it works. Thank you! I'll post here the steps needed in case someone else is interested:

In the server side (supossing Ubuntu)
1. Setup the "Desktop sharing preferences" (vino-preferences), allowing users to control the desktop remotely and setup a password. It runs a vnc server at port 5900 by default.
2. Setup automatic login for the required user

In the _client side_ (supossing again Ubuntu)
1. Install "vinagre", or your preferred vncviewer
2. SSH to the server with port forwarding: `ssh -L 5900:127.0.0.1:5900 user@server_host`
3. Run "vinagre" and connect to localhost:5900
