### ISSUE TITLE
Angle of view of virtual camera

### ISSUE THREAD

**Issue by Anuragch** [uji-ros-pkg/underwater_simulation#39]
I was trying to change virtual camera <parameter>  but there is no change in angle of view of camera .Please help me regarding this .

**Comment by perezsolerj** [comment]
Hi,

Yes, it seems fov is still hard-coded if not using intrinsic parameters in config file. Using "parameters" tag you should be able to change it, if I'm not wrong angle of view on x axis is arctan((width/2)/fx), same for y ayis using height and fy. By now, virtual cameras have a fixed angle of view of 50 on y axis and aspect ratio 1.33, I will add a config parameter on XML so it can be changed and aspect ratio depends on width and height.

Thanks for reporting.
