### ISSUE TITLE
New structure for XML parsing - Vehicle sensors - ROSInterfaces

### ISSUE THREAD

**Issue by marioprats** [uji-ros-pkg/underwater_simulation#4]
The current class structure for XML parsing is quite simple. It is very tedious to add a new sensor, since a lot of files need to be modified (ConfigXMLParser, SimulatedIAUV, SceneBuilder, ROSInterfaces). It would be nice to have a clear interface for new sensors that automatically parses the XML, add the objects to the scene and creates the ROS interfaces.

A developer could then implement that interface for easily adding new sensors.

**Comment by tut-yury** [comment]
I am working on such change and will make a pull request very soon...
UPDATE: pull request submitted...

**Comment by marioprats** [comment]
This seems to be easier with the plugin system @tut-yury implemented. See SimDev_Echo.cpp for an example. Closing!
