### ISSUE TITLE
TF frames should be generated for sensors

### ISSUE THREAD

**Issue by maxpfingsthorn** [uji-ros-pkg/underwater_simulation#41]
Right now, it is necessary to edit the URDF to have proper TF frames for sensors. Also, using the Girona500 example, TF prefixes are added after the fact, making "hardcoding" TF frames in the xml difficult.

It would be great if uwsim could check if a referenced TF frame in the sensor definition exists already, and generate one (with the configured pose and parent frame) if it does not, while respecting the naming conventions (i.e. include the prefix as well). Maybe a warning should be issued if the frame does exist, but does not have the same pose relative to the frame mentioned in the relativeTo tag.

**Comment by perezsolerj** [comment]
Hi Max,

We are planning to add full support for sensors TF publishing soon. By now cameras, multibeam and laser sensors are already being published altough they are referenced to vehicle instead of relativeTo tag. Thanks for your suggestion.
