### ISSUE TITLE
Ocean surface physics

### ISSUE THREAD

**Issue by vinayraousc** [uji-ros-pkg/underwater_simulation#48]
Hey,
I'm trying to use uwsim for simulation of a surface vessel. Is there any way to configure the scene to make the vessel react to the waves? I have enablePhysics=1, but there are no visible effects like buoyancy. Is this something that has already been implemented or will it be a useful feature for uwsim?

**Comment by perezsolerj** [comment]
Hi,
Unfortunately we didn't have time to add buoyancy effects to objects, and underwater vehicle dynamics package only simulates buoyancy for vehicles and considers the vehicle a sphere (for buoyancy) when it's near the surface. 

You can test this dynamics package launching "roslaunch underwater_vehicle_dynamics UWSim_g500_dynamics.launch" and move the vehicle pressing "wasd" and arrow keys (in the terminal window). But as I said doesn't seem realistic for vessel vehicles as it does not take into account waves and vehicle geometry.

Of course it would be a useful feature ;).
