### ISSUE TITLE
No Ocean Floor Physics

### ISSUE THREAD

**Issue by zserlin** [uji-ros-pkg/underwater_simulation#56]
I am trying to create an ocean floor that interacts with the ROV. I have tried a number of things (including putting in another object that acts as a bottom, and making the floor kinematic). None of these have resulted in a seafloor that my ROV interacts with (more than passing right through it). The floor is either fixed but does not interact or interacts but falls infinitely under gravity. I was wondering how the floor was created in the cirs file, and how I might go about creating a solid, fixed object to make a seafloor?

Thank you in advance

**Comment by perezsolerj** [comment]
In order to make vehicles interact with kinematic objects it is necessary to run the dynamics module that controls these kinds of interactions (kinematic - kinematic object in bullet). Take a look at the [wiki](http://www.irs.uji.es/uwsim/wiki/index.php?title=First_steps:_Dynamic_simulation)
