### ISSUE TITLE
Problems about range snesor

### ISSUE THREAD

**Issue by roaddy** [uji-ros-pkg/underwater_simulation#67]
I think ,in default Tank Scene with G500, the virtual range sensor is mounted to Part0 with pitch -1.57 rad. So it is pointing down to measure the distance between ROV and the floor. But when I try to use range sensor as a forward looking sonar, I change the pitch to 0. However, the data from topic doesn't change at all. It seems that it still feedback the distance between ROV and floor. I wonder how to use range sonar as FLS?

**Comment by jake3991** [comment]
Did you make any progress on this? I'm also looking to utilize this system with a forward looking imaging sonar.

**Comment by roaddy** [comment]
> Did you make any progress on this? I'm also looking to utilize this system with a forward looking imaging sonar.

Sorry, I didn't work on it.
